node('mac-local') {
    
    REPO_URL="${env.WORKSPACE}/playing-with-aws"
    ENV_FILE="${env.WORKSPACE}/demo.env"

    stage('Clone') {
        // sh "git clone /Users/omarzl/Documents/aws/playing-with-aws"
    }

    stage('Setup') {
        sh "$REPO_URL/jenkins/mac/setup.sh"
    }

    stage('Clean up') {
        // cleanWs()
    }
}